# Change these first
owner: ilger04 # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:

  - name: OPENSIPA3
    url: $OPENSIPA3

  - name: OPENSIPA1
    url: $OPENSIPA1

  - name: CENTROATI2
    url: $CENTROATI2

  - name: HOTELTURIST2_ILGER
    url: $HOTELTURIST2_ILGER

  - name: NUMBER1_WEB3
    url: $NUMBER1_WEB3

  - name: ATOMINFORMATICA4
    url: $ATOMINFORMATICA4

  - name: SMTP7_ILGER
    check: "tcp-ping"
    url: $SMTP7_ILGER
    port: 25

  - name: SMTP8_ILGER
    check: "tcp-ping"
    url: $SMTP8_ILGER
    port: 25

  - name: SMTP9_ILGER
    check: "tcp-ping"
    url: $SMTP9_ILGER
    port: 25

  - name: SMTP10_ILGER
    check: "tcp-ping"
    url: $SMTP10_ILGER
    port: 25

  - name: SMTP11_ILGER
    check: "tcp-ping"
    url: $SMTP11_ILGER
    port: 25

  - name: VCLOUD_ILGER
    url: $VCLOUD_ILGER

  - name: SOLUZIONE_VDA2
    url: $SOLUZIONE_VDA2

  - name: MACPETS01
    url: $MACPETS01

  - name: AAASERVICE01
    url: $AAASERVICE01

  - name: CLOUDOFFICE02
    url: $CLOUDOFFICE02

  - name: CLD_SCN1
    check: "tcp-ping"
    url: $CLD_SCN1
    port: 25

  - name: CLD_SCN2
    check: "tcp-ping"
    url: $CLD_SCN2
    port: 25

  - name: CLD_SCN8
    check: "tcp-ping"
    url: $CLD_SCN8
    port: 25

  - name: CLD_SCN9
    check: "tcp-ping"
    url: $CLD_SCN9
    port: 25

  - name: CLD_SCN_10
    check: "tcp-ping"
    url: $CLD_SCN_10
    port: 25

  - name: CLD_SCN_11
    check: "tcp-ping"
    url: $CLD_SCN_11
    port: 25

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  name: ilger
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  baseUrl: /Uptime
  icon: https://www.ilger.com/wp-content/uploads/2022/03/ilger-logo-favicon.png
  introTitle: "Page - 5"
  introMessage: Servers Status page with **real-time** data

  navbar:
     - title: Page1
       href: https://ilger-supporto.github.io/Uptime/
     - title: Page2
       href: https://ilger01.github.io/Uptime/
     - title: Page3
       href: https://ilger02.github.io/Uptime/
     - title: Page4
       href: https://ilger03.github.io/Uptime/
     - title: Page5
       href: /Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
